CREATE TABLE IF NOT EXISTS cross_entry_failover_group (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id INT NOT NULL,
  name VARCHAR(100) NOT NULL,
  domain VARCHAR(253) NOT NULL,
  zone_id VARCHAR(64) NOT NULL,
  record_id VARCHAR(64) NOT NULL,
  api_token VARCHAR(2048) NOT NULL,
  record_type VARCHAR(8) NOT NULL DEFAULT 'A',
  ttl INT NOT NULL DEFAULT 60,
  probe_interval_ms INT NOT NULL DEFAULT 2000,
  connect_timeout_ms INT NOT NULL DEFAULT 1200,
  failure_threshold INT NOT NULL DEFAULT 2,
  recovery_threshold INT NOT NULL DEFAULT 3,
  cooldown_seconds INT NOT NULL DEFAULT 30,
  auto_failback TINYINT NOT NULL DEFAULT 0,
  enabled TINYINT NOT NULL DEFAULT 1,
  state VARCHAR(24) NOT NULL DEFAULT 'unknown',
  active_member_id BIGINT DEFAULT NULL,
  last_error VARCHAR(500) DEFAULT NULL,
  last_checked_at BIGINT DEFAULT NULL,
  last_switch_at BIGINT DEFAULT NULL,
  created_time BIGINT NOT NULL,
  updated_time BIGINT NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_cross_entry_domain (domain, record_type),
  KEY idx_cross_entry_due (enabled, last_checked_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS cross_entry_failover_member (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  group_id BIGINT NOT NULL,
  forward_id BIGINT NOT NULL,
  priority INT NOT NULL,
  entry_node_id BIGINT NOT NULL,
  entry_host VARCHAR(255) NOT NULL,
  entry_address VARCHAR(128) NOT NULL,
  entry_port INT NOT NULL,
  forward_name VARCHAR(100) NOT NULL,
  node_name VARCHAR(100) NOT NULL,
  status VARCHAR(24) NOT NULL DEFAULT 'unknown',
  fail_count INT NOT NULL DEFAULT 0,
  success_count INT NOT NULL DEFAULT 0,
  latency_ms INT DEFAULT NULL,
  last_error VARCHAR(500) DEFAULT NULL,
  last_checked_at BIGINT DEFAULT NULL,
  last_healthy_at BIGINT DEFAULT NULL,
  last_failure_at BIGINT DEFAULT NULL,
  created_time BIGINT NOT NULL,
  updated_time BIGINT NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_cross_entry_member (group_id, forward_id),
  KEY idx_cross_entry_member_group (group_id, priority)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS cross_entry_failover_event (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  group_id BIGINT NOT NULL,
  from_member_id BIGINT DEFAULT NULL,
  to_member_id BIGINT DEFAULT NULL,
  from_node_name VARCHAR(100) DEFAULT NULL,
  to_node_name VARCHAR(100) DEFAULT NULL,
  reason VARCHAR(255) NOT NULL,
  status VARCHAR(24) NOT NULL,
  detail VARCHAR(500) DEFAULT NULL,
  created_time BIGINT NOT NULL,
  PRIMARY KEY (id),
  KEY idx_cross_entry_event_group (group_id, created_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
