CREATE TABLE IF NOT EXISTS quality_probe_task (
  id bigint unsigned NOT NULL AUTO_INCREMENT,
  name varchar(100) NOT NULL,
  source_node_id bigint NOT NULL,
  target_type varchar(16) NOT NULL DEFAULT 'custom',
  target_node_id bigint DEFAULT NULL,
  target_host varchar(253) NOT NULL,
  port int NOT NULL,
  protocol varchar(12) NOT NULL,
  path varchar(512) NOT NULL DEFAULT '/',
  server_name varchar(253) DEFAULT NULL,
  ip_family varchar(8) NOT NULL DEFAULT 'auto',
  sample_count int NOT NULL DEFAULT 5,
  timeout_ms int NOT NULL DEFAULT 5000,
  interval_minutes int NOT NULL DEFAULT 15,
  retention_days int NOT NULL DEFAULT 30,
  enabled tinyint NOT NULL DEFAULT 0,
  running tinyint NOT NULL DEFAULT 0,
  next_run_at bigint DEFAULT NULL,
  last_run_at bigint DEFAULT NULL,
  last_status varchar(16) NOT NULL DEFAULT 'pending',
  last_error varchar(500) DEFAULT NULL,
  created_time bigint NOT NULL,
  updated_time bigint NOT NULL,
  PRIMARY KEY (id),
  KEY idx_quality_task_due (enabled,running,next_run_at),
  KEY idx_quality_task_source (source_node_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS quality_probe_run (
  id bigint unsigned NOT NULL AUTO_INCREMENT,
  task_id bigint NOT NULL,
  status varchar(16) NOT NULL,
  source_node_id bigint NOT NULL,
  source_node_name varchar(120) NOT NULL,
  source_line varchar(160) DEFAULT NULL,
  target_host varchar(253) NOT NULL,
  resolved_address varchar(128) DEFAULT NULL,
  ip_family varchar(8) NOT NULL,
  protocol varchar(12) NOT NULL,
  dns_ms decimal(12,3) NOT NULL DEFAULT 0,
  tcp_avg_ms decimal(12,3) DEFAULT NULL,
  tls_avg_ms decimal(12,3) DEFAULT NULL,
  ttfb_avg_ms decimal(12,3) DEFAULT NULL,
  p50_ms decimal(12,3) DEFAULT NULL,
  p95_ms decimal(12,3) DEFAULT NULL,
  p99_ms decimal(12,3) DEFAULT NULL,
  jitter_ms decimal(12,3) NOT NULL DEFAULT 0,
  failure_rate decimal(7,3) NOT NULL DEFAULT 0,
  success_count int NOT NULL DEFAULT 0,
  sample_count int NOT NULL DEFAULT 0,
  http_status int DEFAULT NULL,
  error varchar(500) DEFAULT NULL,
  started_at bigint NOT NULL,
  finished_at bigint NOT NULL,
  PRIMARY KEY (id),
  KEY idx_quality_run_task (task_id,started_at),
  KEY idx_quality_run_source (source_node_id,started_at),
  KEY idx_quality_run_window (started_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS quality_probe_sample (
  id bigint unsigned NOT NULL AUTO_INCREMENT,
  run_id bigint NOT NULL,
  task_id bigint NOT NULL,
  sample_index int NOT NULL,
  success tinyint NOT NULL,
  tcp_ms decimal(12,3) DEFAULT NULL,
  tls_ms decimal(12,3) DEFAULT NULL,
  ttfb_ms decimal(12,3) DEFAULT NULL,
  total_ms decimal(12,3) DEFAULT NULL,
  http_status int DEFAULT NULL,
  error varchar(500) DEFAULT NULL,
  created_time bigint NOT NULL,
  PRIMARY KEY (id),
  KEY idx_quality_sample_run (run_id),
  KEY idx_quality_sample_task (task_id,created_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
