FROM eclipse-temurin:21-jre-alpine

WORKDIR /app
ENV JAVA_OPTS="-Xms64m -Xmx256m -XX:+UseSerialGC -Dfile.encoding=UTF-8 -Duser.timezone=Asia/Shanghai"

RUN apk add --no-cache fontconfig ttf-dejavu

COPY target/*.jar app.jar

EXPOSE 6365
ENTRYPOINT ["sh", "-c", "exec java $JAVA_OPTS -jar /app/app.jar"]
