CREATE TABLE IF NOT EXISTS home_proxy_route (
  id bigint unsigned NOT NULL AUTO_INCREMENT,
  user_id int NOT NULL,
  name varchar(100) NOT NULL,
  connector_id bigint NOT NULL,
  access_mode varchar(24) NOT NULL DEFAULT 'relay',
  ingress_pool_id bigint DEFAULT NULL,
  egress_pool_id bigint NOT NULL,
  lease_id bigint DEFAULT NULL,
  public_port int DEFAULT NULL,
  egress_lease_id bigint DEFAULT NULL,
  egress_gateway_port int DEFAULT NULL,
  direct_ipv6 varchar(64) DEFAULT NULL,
  direct_port int DEFAULT NULL,
  ipv6_checked_at bigint DEFAULT NULL,
  proxy_type varchar(16) NOT NULL DEFAULT 'socks5',
  auth_enabled tinyint NOT NULL DEFAULT 0,
  auth_username varchar(64) DEFAULT NULL,
  auth_password varchar(128) DEFAULT NULL,
  state varchar(24) NOT NULL DEFAULT 'provisioning',
  last_error varchar(500) DEFAULT NULL,
  created_time bigint NOT NULL,
  updated_time bigint NOT NULL,
  PRIMARY KEY (id),
  KEY idx_home_proxy_user (user_id, state),
  KEY idx_home_proxy_connector (connector_id, state),
  KEY idx_home_proxy_lease (lease_id),
  KEY idx_home_proxy_egress_lease (egress_lease_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
